- name: Wordpress and Node Exporter
  become: true
  hosts: node-servers
  roles:
    - docker
    - docker_compose
    - wordpress
    - node_exporter

- name: Prometheus and Grafana
  become: true
  hosts: monitor-server
  roles:
    - prometheus
    - grafana
